### ISSUE TITLE
coffeedoc.info down?

### ISSUE THREAD

**Issue by meetshawn** [coffeedoc/coffeedoc.info#10]
> 400
> www.coffeedoc.info is currently stopped

**Comment by Zorbash** [comment]
Any updates on this? Is there anything we can do to help?

**Comment by inossidabile** [comment]
Well. Nodejitsu seems to be down... It needs to be redeployed to any other free hoster allowing to run web service and queue service

**Comment by inossidabile** [comment]
In fact there's nothing we can do. The domain itself isn't available anymore. Only Michael had access to it... I'm sorry to say that but looks like `coffeedoc.info` won't be available soon.

**Comment by Zorbash** [comment]
I'm willing to host it, maybe set a mirror domain. What do you think @netzpirat ?

**Comment by inossidabile** [comment]
We are up for hosting a mirror, Zorbash.
