### ISSUE TITLE
coffeedoc.info is down! nodejitsu returns 400

### ISSUE THREAD

**Issue by topliceanu** [coffeedoc/coffeedoc.info#9]

**Comment by effkay** [comment]
Hi @topliceanu 

I just fixed an issue with the nodejitsu account. Is the API working for you again?

**Comment by topliceanu** [comment]
Yes it is, i't generating the docs. 10x

**Comment by aseemk** [comment]
Thank you very much @effkay. Much appreciated. I think it'd be safe to close this issue now.

**Comment by aseemk** [comment]
Btw, to others that didn't know (like me), unfortunately @netzpirat passed away last year. =(

https://groups.google.com/forum/#!topic/guard-dev/2Td0QTvTIsE

Thank you @inossidabile, @effkay, and anyone else who has helped take over maintenance duties of Codo and CoffeeDoc.info. It's a great project.

**Comment by topliceanu** [comment]
Ok, closing this.
